# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8888
    volumes:
      - app:/app
    ports:
      - "8899:8888"

volumes:
  app: